"""empty message

Revision ID: 6282ad202737
Revises: e9c151530344
Create Date: 2021-01-28 00:47:45.144360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6282ad202737'
down_revision = 'e9c151530344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'official',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'official',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
