"""empty message

Revision ID: b9191d2d3789
Revises: f845c2fe7c2f
Create Date: 2020-11-13 21:45:33.636266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9191d2d3789'
down_revision = 'f845c2fe7c2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('community', sa.Column('confirm', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('community', 'confirm')
    # ### end Alembic commands ###
