"""empty message

Revision ID: e9c151530344
Revises: e08a015bacff
Create Date: 2021-01-28 00:28:52.059539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9c151530344'
down_revision = 'e08a015bacff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('official', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'official')
    # ### end Alembic commands ###
